(function () {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const next = new URLSearchParams(location.search).get("next");
  const escape = (value) => String(value || "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char]));
  async function api(path, options) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", ...(options && options.headers) } }); const data = await response.json(); if (!response.ok) { const error = new Error(data.error || "Request failed"); error.status = response.status; error.data = data; throw error; } return data; }
  function showError(form, message) { form.querySelector(".auth-error").textContent = message || ""; }
  function showAuth() { $("#auth-view").hidden = false; $("#account-view").hidden = true; }
  function showVerification(email) { $("#login-form").hidden = true; $("#register-form").hidden = true; $("#verify-form").hidden = false; $("#verify-email").textContent = email; $("#verify-form").dataset.email = email; $("#verify-form").elements.code.focus(); }
  async function loadBookings() { const { bookings } = await api("/api/me/bookings"); const labels = { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", cancelled: "Đã hủy" }; $("#customer-bookings").innerHTML = bookings.length ? bookings.map((booking) => `<article class="customer-booking"><div><h3>${escape(booking.propertyName)}</h3><p>${escape(booking.checkin)} → ${escape(booking.checkout)} · ${booking.nights} đêm · ${booking.guests} khách</p><span class="booking-status ${booking.status}">${labels[booking.status] || escape(booking.status)}</span></div><div><p>Mã đặt chỗ</p><strong>${escape(booking.reference)}</strong><p>Tổng cộng ${escape(booking.total)}</p></div><div class="customer-actions"><a href="/api/me/bookings/${encodeURIComponent(booking.id)}/receipt" target="_blank" rel="noopener">Xem biên nhận</a>${booking.status !== "cancelled" ? `<button class="cancel" data-cancel="${booking.id}">Hủy đặt chỗ</button>` : ""}</div></article>`).join("") : '<div class="no-bookings">Bạn chưa có đặt chỗ nào. Hãy bắt đầu bằng cách khám phá các căn hộ.</div>'; document.querySelectorAll("[data-cancel]").forEach((button) => button.addEventListener("click", async () => { if (!confirm("Hủy đặt chỗ này? Khoảng ngày đó sẽ được mở lại.")) return; try { await api(`/api/me/bookings/${encodeURIComponent(button.dataset.cancel)}`, { method: "PATCH", body: JSON.stringify({ status: "cancelled" }) }); await loadBookings(); } catch (error) { alert(error.message); } })); }
  async function showAccount(user) { $("#auth-view").hidden = true; $("#account-view").hidden = false; $("#customer-name").textContent = user.name; $("#customer-email").textContent = user.email; await loadBookings(); }
  async function init() { try { const { user } = await api("/api/auth/me"); if (user.role !== "customer") throw new Error("Tài khoản quản trị"); await showAccount(user); } catch { showAuth(); } }
  document.querySelectorAll("[data-auth-tab]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll("[data-auth-tab]").forEach((item) => item.classList.toggle("active", item === button)); $("#verify-form").hidden = true; $("#login-form").hidden = button.dataset.authTab !== "login"; $("#register-form").hidden = button.dataset.authTab !== "register"; }));
  $("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; showError(form); const F = form.elements; try { const { user } = await api("/api/auth/login", { method: "POST", body: JSON.stringify({ email: F.email.value, password: F.password.value }) }); if (next) location.href = next; else await showAccount(user); } catch (error) { if (error.data && error.data.verificationRequired) showVerification(error.data.email); else showError(form, error.message); } });
  $("#register-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; showError(form); const F = form.elements; try { const result = await api("/api/auth/register", { method: "POST", body: JSON.stringify({ name: F.name.value, email: F.email.value, password: F.password.value }) }); showVerification(result.email); } catch (error) { showError(form, error.message); } });
  $("#verify-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; showError(form); try { const { user } = await api("/api/auth/verify-email", { method: "POST", body: JSON.stringify({ email: form.dataset.email, code: form.elements.code.value }) }); if (next) location.href = next; else await showAccount(user); } catch (error) { showError(form, error.message); } });
  $("#resend-code").addEventListener("click", async () => { const form = $("#verify-form"); showError(form); try { await api("/api/auth/resend-verification", { method: "POST", body: JSON.stringify({ email: form.dataset.email }) }); showError(form, "Mã xác minh mới đã được gửi."); } catch (error) { showError(form, error.message); } });
  $("#logout").addEventListener("click", async () => { await api("/api/auth/logout", { method: "POST", body: "{}" }); location.reload(); });
  init();
})();
